### ISSUE TITLE
Completar PDF

### ISSUE THREAD

**Issue by HebePereyra** [ISPC-PROYECTOS/controlStockGranel#3]
Completar Presentacion Base de datos del proyecto, sus diagramas y SQL.pdf con los requerimiento de la consigna .(ya creado) solo completar.

**Comment by HebePereyra** [comment]
Creacion de documento presentaciones en Drive colavorativo con consiganas separadas por diapositiva. (Ulises, Consu, Hebe)

**Comment by dataulix** [comment]
Se corroboró el funcionamiento de la Base de Datos "stockgranel", se consultaron las tablas con datos y se generaron las imágenes de cada una de ellas para el documento.

**Comment by ConsueloViramont** [comment]
Se controlo que las funcionalidades esten correctas.
