### ISSUE TITLE
HACER VIDEO

### ISSUE THREAD

**Issue by HebePereyra** [ISPC-PROYECTOS/controlStockGranel#8]
REUNION POR MEET.

**Comment by HebePereyra** [comment]
DISCULPEN, REUNION POR ZOOM.

**Comment by dataulix** [comment]
Conectarse bañad@, peinad@ y perfumad@ para el video grupal !

**Comment by ConsueloViramont** [comment]
Listos para el zoom! Perfumados!

**Comment by jesivaldi** [comment]
El video ha sido finalizado.

- El video está completo y revisado.
Cierro este issue ya que el trabajo está terminado.

Gracias.

**Comment by ConsueloViramont** [comment]
Video subido.
